### PR TITLE
Fix warning, removed unusued variable

### PR DESCRIPTION
**Pull request by Helias**

### CODE REVIEW

**Comment by Kaev** [comment]
Best practice is to delete unneeded code instead of commenting it out.

**Comment by Helias** [comment]
I know, but maybe the author could use it another time xD, I don't know why it is there.
Anyway, I'm deleting it, thx

**Comment by wizzymore** [comment]
Hi,

The problem with this module is vast and it needs a re-work on it, and as i made the code in the shitty it is now, i feel obligated to fix this and i am working on code improvement for this.

I will close this PR as it will be useless for the moment ( as the build doesn't work and when it works the server crashes all the time )

As a side note, even if you ( the reader ) make this module build, your have the risk of sql injection on your own skin as i don't recommend this module, not safe and not working ( for the moment ).

Thank you for looking into this!

**Comment by BarbzYHOOL** [comment]
yeah there is sql injection on this one like mentioned here https://github.com/azerothcore/mod-npc-codebox/issues/1

**Pull request closed without merging**
