### PR TITLE
Fixing build errors and resolving TO-DO list

### PR DESCRIPTION
**Pull request by wizzymore**
I resolved some of the TO-DO from @StygianTheBest list. Those modifications are live on his main repo and they work 100%.

In addition i fixed the linux clang build errors, now everything works as intended.

Everyhing work as intended, the fixes and update is even on the main repo from Styx, https://github.com/StygianTheBest/mod-npccodebox

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
commit name: "Big update"

:'(

We could just sync with Stygian's repo though as this module has not been modified by anybody but me

**Comment by milestorme** [comment]
Can we merge this I didn’t see this when I did my pull request. Closing mine.

**Comment by BarbzYHOOL** [comment]
@milestorme @wizzymore shouldn't we just create a PR from stygian's repo? (it has more stuff)

**Comment by milestorme** [comment]
I guess we could do that , then apply wizzy’s clean up stygiancore codebox needed some love I believe wizz fixed in his commit , he would have to add those after you merge stygians

**Comment by milestorme** [comment]
thank you @wizzymore tested and will use

**Pull request merged**
